version: '3.8'
services:
  backend:
    build:
      context: ../backend-new
      dockerfile: Dockerfile
    ports: ["3000:3000"]
    environment:
      - FRONTEND_URL=http://localhost:3001
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=1234
      - DB_NAME=moneyflow
      - JWT_SECRET=tu_clave_secreta
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ../frontend-new
      dockerfile: Dockerfile
    ports: ["3001:3000"]
    environment:
      - VITE_API_URL=http://backend:3000/api
      - VITE_FRONTEND_URL=http://localhost:3001
    depends_on:
      backend:
        condition: service_started

  db:
    image: postgres:13
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=moneyflow
      - POSTGRES_USER=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d moneyflow"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: