version: '3.8'
services:
  backend:
    build:
      context: ../moneyflow-backend
      dockerfile: Dockerfile
    ports: ["3000:3000"]
    env_file: ../moneyflow-backend/.env
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ../moneyflow-frontend
      dockerfile: Dockerfile
    ports: ["3001:3000"]
    env_file: ../moneyflow-frontend/.env
    depends_on:
      backend:
        condition: service_started

  db:
    image: postgres:13
    env_file: ../moneyflow-backend/.env.db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: