name: Integration Test
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Checkout Subrepos
        run: |
          git clone https://github.com/Emadlgg/MoneyFlow_Backend.git ../moneyflow-backend
          git clone https://github.com/Emadlgg/MoneyFlow_Frontend.git ../moneyflow-frontend
      - name: Start Services
        run: docker-compose up --build -d
      - name: Run Backend Tests
        run: docker-compose exec backend npm test
      - name: Run Frontend Tests
        run: docker-compose exec frontend npm test
